#!/data/data/com.termux/files/usr/bin/env bash
# Install a boot-time persistence script for the detected root manager so
# the Termux MLS contexts get re-applied to AI CLI binaries on every boot.
#
# Without this, app auto-updaters (Claude, agy, etc) write files under su
# that come back without Termux MLS categories, and Termux user sessions
# get 'exec: Operation not permitted' on the next launch.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
. "$HERE/../lib/common.sh"

banner "Install permanent boot persistence"

require_root

SERVICE_DIR=$(detect_service_dir)
if [ -z "$SERVICE_DIR" ]; then
  log_err "No supported root manager detected (Magisk / KernelSU / APatch)."
  log_err "Manual fix: drop a script in your root manager's boot hook directory"
  log_err "that runs: bash $HERE/50-persistence.sh apply-mls"
  exit 1
fi

CTX=$(detect_termux_mls_context)
TERMUX_USER=$(detect_termux_user)
HOOK="$SERVICE_DIR/root-aicli-persist.sh"

log_info "Writing boot hook to $HOOK"
log_info "  Termux user: $TERMUX_USER"
log_info "  MLS context: $CTX"

cat > "$HOOK" <<EOF
#!/system/bin/sh
# Auto-generated by Root.AICLI. Re-applies Termux MLS categories to all AI CLI
# binaries on every boot, so Termux can exec them after auto-updates.
TERMUX=/data/data/com.termux/files
ALP=\$TERMUX/usr/var/lib/proot-distro/containers/alpine/rootfs
CTX="$CTX"
TERMUX_USER="$TERMUX_USER"

# Wait for /data to be decrypted (FBE devices unlock asynchronously).
while [ ! -d "\$TERMUX/home" ]; do sleep 5; done
sleep 10

for tree in \$TERMUX/home/.local \$TERMUX/home/.grok \$TERMUX/home/.codex \
            \$TERMUX/usr/bin \$ALP/root/.local \$ALP/usr/local/bin; do
  [ -d "\$tree" ] || continue
  find "\$tree" 2>/dev/null | while read f; do
    chown -h \$TERMUX_USER:\$TERMUX_USER "\$f" 2>/dev/null
    chcon -h "\$CTX" "\$f" 2>/dev/null
  done
done
EOF

chmod 755 "$HOOK"
ls -la "$HOOK"
log_ok "Boot hook installed. Will run on next reboot. Also applying once now..."

# Run it now so the user doesn't have to reboot to see effects
bash "$HOOK"

log_ok "Permanent persistence enabled. Auto-updates from CLIs will not break Termux exec."
