#!/data/data/com.termux/files/usr/bin/env bash
# Install a boot-time persistence script for the detected root manager so
# the Termux MLS contexts get re-applied to AI CLI binaries on every boot.
#
# Without this, app auto-updaters (Claude, agy, etc) write files under su
# that come back without Termux MLS categories, and Termux user sessions
# get 'exec: Operation not permitted' on the next launch.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
. "$HERE/../lib/common.sh"

banner "Install permanent boot persistence"

require_root

SERVICE_DIR=$(detect_service_dir)
if [ -z "$SERVICE_DIR" ]; then
  log_err "No supported root manager detected (Magisk / KernelSU / APatch)."
  log_err "Manual fix: drop a script in your root manager's boot hook directory"
  log_err "that runs: bash $HERE/50-persistence.sh apply-mls"
  exit 1
fi

CTX=$(detect_termux_mls_context)
TERMUX_USER=$(detect_termux_user)
HOOK="$SERVICE_DIR/root-aicli-persist.sh"

log_info "Writing boot hook to $HOOK"
log_info "  Termux user: $TERMUX_USER"
log_info "  MLS context: $CTX"

cat > "$HOOK" <<EOF
#!/system/bin/sh
# Auto-generated by Root.AICLI. Heals two common Termux brokens on every boot:
#
#  1. Termux's apt sometimes lands .so files with mode 600 (no execute).
#     The dynamic linker can't mmap them with PROT_EXEC, so bash and any
#     binary that depends on the affected .so fails with "library X not found".
#
#  2. Anything written under su (Anthropic auto-update, Root.AICLI itself,
#     unattended package upgrades) lands with the no-categories
#     u:object_r:app_data_file:s0 context. Termux's app SELinux domain
#     requires matching MLS categories or it gets "permission denied"
#     disguised as "no such file or directory."
#
TERMUX=/data/data/com.termux/files
ALP=\$TERMUX/usr/var/lib/proot-distro/containers/alpine/rootfs
CTX="$CTX"
TERMUX_USER="$TERMUX_USER"

# Wait for /data to be decrypted (FBE devices unlock asynchronously).
while [ ! -d "\$TERMUX/home" ]; do sleep 5; done
sleep 10

# Heal .so file permissions in \$PREFIX/lib. 600 -> 644 so dyn linker can map.
find \$TERMUX/usr/lib -type f -perm 600 -exec chmod 644 {} + 2>/dev/null

# Heal MLS contexts across \$PREFIX and Termux home, plus Alpine helpers.
# This is a sledgehammer: re-label EVERYTHING under \$PREFIX with the Termux
# MLS context so any file written without categories gets fixed up.
for tree in \$TERMUX/usr/lib \$TERMUX/usr/bin \$TERMUX/usr/libexec \
            \$TERMUX/usr/etc \$TERMUX/usr/var \
            \$TERMUX/home/.local \$TERMUX/home/.grok \$TERMUX/home/.codex \
            \$TERMUX/home/.claude \$TERMUX/home/root-aicli \
            \$ALP/root/.local \$ALP/usr/local/bin; do
  [ -d "\$tree" ] || continue
  find "\$tree" 2>/dev/null | while read f; do
    chown -h \$TERMUX_USER:\$TERMUX_USER "\$f" 2>/dev/null
    chcon -h "\$CTX" "\$f" 2>/dev/null
  done
done
EOF

# Alpine mode: also reassert the Termux -> Alpine claude dispatcher on every
# boot so a native `claude` self-update can't shadow it in PATH (20-claude.sh).
if [ "$(detect_runtime_preference)" = "alpine" ]; then
  log_info "Alpine mode: boot hook will also reassert the claude dispatcher"
  cat >> "$HOOK" <<'HOOKX'

# --- claude dispatcher reassert (Root.AICLI, alpine mode) ---
CANON=$TERMUX/usr/libexec/root-aicli/claude-dispatcher
if [ -f "$CANON" ]; then
  for p in "$TERMUX/home/.local/bin/claude" "$TERMUX/home/bin/claude" "$TERMUX/usr/bin/claude"; do
    d=$(dirname "$p"); [ -d "$d" ] || mkdir -p "$d"
    rm -f "$p"; cp "$CANON" "$p"; chmod 755 "$p"
    chown "$TERMUX_USER":"$TERMUX_USER" "$p" 2>/dev/null
    chcon "$CTX" "$p" 2>/dev/null
  done
fi
HOOKX
fi

chmod 755 "$HOOK"
ls -la "$HOOK"
log_ok "Boot hook installed. Will run on next reboot. Also applying once now..."

# Run it now so the user doesn't have to reboot to see effects
bash "$HOOK"

log_ok "Permanent persistence enabled. Auto-updates from CLIs will not break Termux exec."
